baseURL: "https://mamorum.github.io/txt/"
locale: "ja-jp"
title: "ma- / 松永夜"
theme: "PaperMod"

services:
  googleAnalytics:
    id: "G-9675B7814P"

markup:
  goldmark:
    renderer:
      unsafe: true
      hardWraps: true

languages:
  ja:
    label: "日本語"
    weight: 1

params:
  ShowRssButtonInSectionTermList: true
  showPostNavLinks: true
  homeInfoParams:
    Title: "詩の作品集"
    Content: |
      詩を書いて投稿しています。よろしくお願いします。
      - <a target="_blank" href="https://x.com/ma2yoru">X</a>
      - <a target="_blank" href="https://note.com/ma2yoru">Note</a>
      - [PrivacyPolicy]({{< relref "privacy" >}})

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Archive"
      url: "/archives/"
      weight: 2
    - name: "Tags"
      url: "/tags/"
      weight: 3
