baseURL: "https://mamorum.github.io/txt/"
locale: "ja-jp"
title: "ma- / 松永夜"
theme: "PaperMod"

services:
  googleAnalytics:
    id: "G-9675B7814P"

markup:
  goldmark:
    renderer:
      unsafe: true
      hardWraps: true

languages:
  ja:
    label: "日本語"
    weight: 1

params:
  mainSections: ["lyrics", "poems"]
  ShowRssButtonInSectionTermList: true
  showPostNavLinks: true
  homeInfoParams:
    Title: "作品集"
    Content: |
      作詞をしたり、詩を書いたりしています。
      よろしくお願いします。
      - <a target="_blank" href="https://x.com/ma134x">X (ma-)</a>
      - <a target="_blank" href="https://x.com/ma2yoru">X (松永夜)</a>
      - [Privacy Policy]({{< relref "privacy" >}})

menu:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "Lyrics"
      url: "/lyrics/"
      weight: 2      
    - name: "Poems"
      url: "/poems/"
      weight: 3
    - name: "Archive"
      url: "/archives/"
      weight: 4
    - name: "Tags"
      url: "/tags/"
      weight: 5
