baseURL = "https://mamorum.github.io/poem/"
locale = "ja-jp"
title = "松永夜"
theme = "PaperMod"


[services]
  [services.googleAnalytics]
    id = "G-9675B7814P"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      hardWraps = true

[params.homeInfoParams]
  Title = "詩の作品集"
  Content = """
詩を書いて投稿しています。よろしくお願いします。
- <a target="_blank" href="https://x.com/ma2yoru">X</a>
- <a target="_blank" href="https://note.com/ma2yoru">Note</a>
- [PrivacyPolicy]({{< relref "privacy" >}})
"""
